spring:
  application:
    name: itoken-service-redis
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 94.191.121.218:26379

server:
  port: 8502

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/